plugins {
    id "org.springframework.boot" version "3.5.4" apply false
    id "io.spring.dependency-management" version "1.1.7"
    id "com.diffplug.spotless" version "7.2.1" apply false
    id "com.google.protobuf" version "0.9.4" apply false
}

allprojects {
    group = 'io.github.makbn'
    version = 'v2.3.0'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'maven-publish'
    apply plugin: 'com.diffplug.spotless'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withJavadocJar()
        withSourcesJar()
    }

    repositories {
        maven { url = uri("https://repo.maven.apache.org/maven2/") }
        maven {
            url = uri("https://repo.e-iceblue.com/nexus/content/groups/public/")
            content { includeGroup "e-iceblue" }
        }
        mavenLocal()
    }

    dependencyManagement {
        imports {
            mavenBom 'org.springframework.boot:spring-boot-dependencies:3.5.4'
            mavenBom 'org.springframework.modulith:spring-modulith-bom:1.4.2'
        }
    }

    dependencies {
        compileOnly "org.projectlombok:lombok:${lombok_ver}"
        annotationProcessor "org.projectlombok:lombok:${lombok_ver}"
        testImplementation platform("org.junit:junit-bom:${junit_ver}")
        testImplementation "org.junit.jupiter:junit-jupiter"
        testRuntimeOnly "org.junit.platform:junit-platform-launcher"
        testCompileOnly "org.projectlombok:lombok:${lombok_ver}"
        testAnnotationProcessor "org.projectlombok:lombok:${lombok_ver}"
    }

    test {
        useJUnitPlatform()
        testLogging { events "passed", "skipped", "failed" }
        maxHeapSize = '1G'
    }

    spotless {
        java {
            trimTrailingWhitespace()
            formatAnnotations()
            palantirJavaFormat()
            removeUnusedImports()
            importOrder('', 'org', 'com', '#', 'java', 'javax')
            targetExclude '**/build/generated/**'
        }
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                groupId = 'io.github.makbn'
                artifactId = project.name
                version = '2.3.0'
                pom {
                    name = project.name
                    description = "JThumbnail ${project.name} module"
                    url = 'https://github.com/makbn/JThumbnail'
                    licenses {
                        license {
                            name = 'GNU Lesser General Public License v2.1'
                            url = 'https://github.com/makbn/JThumbnail/blob/master/LICENSE'
                        }
                    }
                    developers {
                        developer {
                            id = 'makbn'
                            name = 'Matt Akbarian'
                            email = 'mehdi74akbarian@gmail.com'
                        }
                    }
                    scm {
                        connection = 'scm:git:https://github.com/makbn/JThumbnail.git'
                        developerConnection = 'scm:git:ssh://github.com/makbn/JThumbnail.git'
                        url = 'https://github.com/makbn/JThumbnail'
                    }
                }
            }
        }
    }
}
