rootProject.name = 'JThumbnail'

include 'jthumbnail-core'
include 'jthumbnail-webservice'
include 'jthumbnail-webhook'
include 'jthumbnail-kafka'
include 'jthumbnail-amqp'
include 'jthumbnail-grpc'
include 'jthumbnail-watcher'
include 'jthumbnail-storage'
include 'jthumbnail-mcp'
include 'jthumbnail-app'
include 'jthumbnail-cdnedge'
include 'jthumbnail-graphql'
include 'jthumbnail-spring-boot-starter'
