dependencies {
    implementation project(':jthumbnail-core')
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdoc_ver}"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
